### ISSUE TITLE
Add a basic world map in 'Overview' page

### ISSUE THREAD

**Issue by subinasr** [collective-service/ifrc-gates-dashboard#11]
- Use Mapbox to include a basic static map

![Image](https://user-images.githubusercontent.com/51225380/178908981-1e8e91cc-eafc-4d96-a3a8-64536b1b4cd2.png)

[Figma Link](https://www.figma.com/proto/GTZyuDH7Ef8gauwAuGnxpV/RCCE-Behavioral-Dashboard_Wires?node-id=2%3A5&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A5)

**Comment by kopitek8** [comment]
Julien: "Gradient based on single indicator
When no indicator is selected and no outbreak, it shows the sum of all cases for all outbreaks.
use https://data.unhcr.org/en/geoservices for the shapefiles"
