### ISSUE TITLE
Epidemiological data in Country page needs to be formatted as in description

### ISSUE THREAD

**Issue by kopitek8** [collective-service/ifrc-gates-dashboard#133]
epidemiological data - tooltip
* format numbers - e.g. 1,935 / 49,039.8
* mention date - e.g. as of July 2022
* data should include new cases, new cases per million, total cases, new deaths, new deaths per million and total deaths

**Comment by ranjan-stha** [comment]
@shreeyash07 new_cases, new_cases_per_million, total_cases, new_deaths, total_deaths, new_deaths_per_million
