### ISSUE TITLE
Bottom/top Ranking

### ISSUE THREAD

**Issue by k9845** [collective-service/ifrc-gates-dashboard#311]
On hovering over the bottom country list; the indicator value should show the exact value without any round-off.
![image](https://user-images.githubusercontent.com/38976661/200737973-8a2a19bc-f11f-412b-83ec-61c054fe3a4f.png)
And the network response is
![image](https://user-images.githubusercontent.com/38976661/200738088-9c505665-3982-4e95-853e-7538126964ff.png)
The issue is for county `China`.

**Comment by kopitek8** [comment]
Always send indicator_id = 'new_case_per_million'
