### ISSUE TITLE
Show more information in indicator progress bar tooltip

### ISSUE THREAD

**Issue by kopitek8** [collective-service/ifrc-gates-dashboard#327]
The "i" tooltip for each indicator should show the full name, as well source and date (similar to tooltip on country contextual indicator) - not an html info box, but a js tooltip that allows hyperlinks

**Comment by ranjan-stha** [comment]
@bimal125 In the existing query for the Combined Indicators where we have data in the subvariable level, we need to attach the source text + date + organization + link from the table `t_data_granular` for each. Note that the sources info are available for the countries and not at the global or regional data level.

**Comment by ranjan-stha** [comment]
@subinasr We already have a query to fetch the sources of the indicator/sub-indicator data in the Country Page (I think Shreeyash implemented that). So, using the same query, in the Combined Indicator page, for each hover on the information icon on the indicator/sub-indicator, we could send a query to fetch this source data in real-time. As it is just a piece of meta data, the response should be pretty quick. cc @kopitek8 @bimal125
