### ISSUE TITLE
Bug in Country Page while displaying most recent data of the Indicator

### ISSUE THREAD

**Issue by Rup-Narayan-Rajbanshi** [collective-service/ifrc-gates-dashboard#365]
In Country Page, whenever we manually change the sub-variable from the drop-down list, the indicator value doesn't change. It seems like the sub-variable is considered in the backend. The frontend does send the sub-variable in the request. To check if this sub-variable is being used in the backend whenever this is passed in the request.

Whenever the indicator is selected (with selecting the sub-variable), we sort the filtered data in ascending order and get the first item from the sorted list from the recent month. This is fine. This has been implemented.

Table: t_data_country_level_most_recent

**Comment by Rup-Narayan-Rajbanshi** [comment]
@ranjan-stha , This is a front end issue. We need to pass filter subvariable in the query

**Comment by ranjan-stha** [comment]
I will move it to done.
