### ISSUE TITLE
Bug in narrative query tracked by Sentry

### ISSUE THREAD

**Issue by ranjan-stha** [collective-service/ifrc-gates-dashboard#368]
Sentry tracked an error in narrative:

Unknown argument 'iso3' on field 'Query.naratives'.

GraphQL request:1:18
1 | query {naratives(iso3: "AFG") {narrative}}
  |                  ^

Bimal suggested that is not the correct way to use the filter in the query:

Also, Bimal has fixed the typo in the narrative query:
So, use this branch: https://github.com/collective-service/ifrc-gates-backend/pull/217  `(fix/typo)`

So, check the filter in the narrative query and see if there is a bug.

Let me know if you have questions.

**Comment by kopitek8** [comment]
# NARRATIVE SHOULD ONLY APPEAR IN THE COUNTRY AND COMBINED INDICATORS PAGE

## Cases

#### When Country is only selected from the admin panel

The narrative should be displayed on country level

#### When Country and Indicator is selected from the admin panel

The narrative should be displayed on country + topic level

## Steps to Replicate

- United States of America
- United States of America + Disease Awareness
- United States of America + Percentage of individuals who seek information about the disease
