### ISSUE TITLE
Overview > Global, Indicator Overview and Regional Breakdown has no data but there is data in Top and Bottom ranking

### ISSUE THREAD

**Issue by Shhhhhubh** [collective-service/ifrc-gates-dashboard#397]
Outbreak ---> COVID-19 
Indicator ---> Percentage of individuals who seek information about the disease 
Sub-indicator ---> Transmission 

![Image](https://user-images.githubusercontent.com/117332528/203744319-0fc49344-7d4e-4c9a-a46a-d96736430d12.png)

**Comment by Shhhhhubh** [comment]
Same case in  
 outbreak ----> COVID-19 
Indicator ----> percentage of individuals who trust information from a given source 
sub indicator ---> NGO

![Image](https://user-images.githubusercontent.com/117332528/203745426-8aa4fafc-b5cc-4346-9acb-bbcb67193f00.png)

**Comment by kopitek8** [comment]
This is a database issue
