### ISSUE TITLE
Create Basic Stat Component in "Country" page

### ISSUE THREAD

**Issue by subinasr** [collective-service/ifrc-gates-dashboard#4]
- Populate with Figma fields

![Image](https://user-images.githubusercontent.com/51225380/178903393-9fdb0ca8-dfd3-4fb5-bc5f-38f5d183355f.png)

[Figma Link](https://www.figma.com/proto/GTZyuDH7Ef8gauwAuGnxpV/RCCE-Behavioral-Dashboard_Wires?node-id=135%3A629&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A5)

**Comment by kopitek8** [comment]
UPDATED screenshot:

Third item 'Death' might change in the future



![Image](https://user-images.githubusercontent.com/25280806/180968507-e0cde540-6151-4ca0-8e22-1f695624dcc8.png)
