### ISSUE TITLE
Create Country Detail View Component

### ISSUE THREAD

**Issue by subinasr** [collective-service/ifrc-gates-dashboard#5]
- Populate with Figma fields

![Image](https://user-images.githubusercontent.com/51225380/178903879-03e37ab7-f70e-402c-bf0b-fd0b31d7ef94.png)

[Figma Link](https://www.figma.com/proto/GTZyuDH7Ef8gauwAuGnxpV/RCCE-Behavioral-Dashboard_Wires?node-id=135%3A629&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A5)

**Comment by kopitek8** [comment]
Julien: "Country map - remove and replace with 4 context indicators"
